import re

# заголовки запроса, прикидываемся браузером
HEADERS = {'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0'}

"""словарь с параметрами парсинга для каждого сайта

ключ словаря (например ctlgrph)- идентефикатор для парсинга конкретного сайта

browse_url - адрес сайта, для сравнения ссылок и выполнения запросов
urls - массив ссылок для просмотра ссылок на статьи
link_to_art - словарь с параметрами тэгов для извлечения ссылок
	tag - тэг
	attr - аттрибут тэга
	attr_value - значение аттрибута тэга
title - словарь с параметрами тэгa для извлечения заголовка
	tag - тэг
	attr - аттрибут тэга
	attr_value - значение аттрибута тэга
body - словарь с параметрами тэгa для извлечения заголовка
	tag - тэг
	attr - аттрибут тэга
	attr_value - значение аттрибута тэга
csv_name - имя файла для сохранение результатов
short_link - True, если ссылки извлекаются без полного адреса

text_func - необязательный ключ, название функции для
	извлечения текста с особыми или неоднородными параметрами.
	Например для http://bitnewsbot.com/
"""

params = {'cointelegraph':
           {'browse_url': 'https://cointelegraph.com/',
			#'urls': [ 'https://www.cointelegraph.com'
			#		],
			'urls_art': [

# 'https://cointelegraph.com/news/cosign_to_introduce_a_new_standard_for_bitcoin_wallet_security',
# 'https://cointelegraph.com/news/denmark_is_determined_to_leave_bitcoin_transactions_free_of_taxes',
# 'https://cointelegraph.com/news/observations_from_auroracoin_s_launch',
# 'https://cointelegraph.com/news/irs_will_tax_cryptocoins_as_property_not_currency',
# 'https://cointelegraph.com/news/gyft_and_walmart_proclaim_cooperation_for_more_possibility_to_spend_bitcoin',
				
# 'https://cointelegraph.com/news/frenchman_prosecuted_for_mentioning_bitcoin_in_conversation',
# 'https://cointelegraph.com/news/bitcoin_feeling_warm_and_fuzzy_in_vietnam',
# 'https://cointelegraph.com/news/with_big_players_on_the_team_coinbase_is_building_a_digital_fortress',
# 'https://cointelegraph.com/news/cyberpowerpc_descends_into_mines',

# 'https://cointelegraph.com/news/biggest_known_bitcoin_purchase_a_500_000_villa',
# 'https://cointelegraph.com/news/emplace_the_flag_of_bitcoin_on_mt_everest',
# 'https://cointelegraph.com/news/european_central_bank_repeats_its_2012_stance_on_digital_currencies',
# 'https://cointelegraph.com/news/did_alan_watts_lay_the_foundations_for_cryptocurrencies_in_the_60s',
# 'https://cointelegraph.com/news/myfinbec_where_art_and_bitcoin_collide',
# 'https://cointelegraph.com/news/andreessen_horowitz_proceeds_to_pour_money_into_bitcoin',
# 'https://cointelegraph.com/news/deja_vu_vircurex_exchange_halts_withdrawals',
# 'https://cointelegraph.com/news/coinlock_makes_selling_data_as_easy_as_few_clicks',
# 'https://cointelegraph.com/news/bitcoin_foundation_introduces_bitpay_as_new_gold_member',
# 'https://cointelegraph.com/news/bitcoin_for_compassion_and_lais_souza',
				
# 'https://cointelegraph.com/news/who_are_you_my_mysterious_bitcoin_user',
# 'https://cointelegraph.com/news/classy_dining_with_bitcoin_in_nashville',
# 'https://cointelegraph.com/news/dubai_has_a_chance_to_receive_the_biggest_bitcoin_atm_network_in_the_world',
# 'https://cointelegraph.com/news/wall_street_journal_presents_myopic_view_on_cryptocurrencies_cash',
# 'https://cointelegraph.com/news/two_top_filipino_retailers_embrace_bitcoin_thanks_to_coin_ph',
# 'https://cointelegraph.com/news/colombia_close_to_outlawing_bitcoin',
# 'https://cointelegraph.com/news/on_wallets_and_safety_part_3_internet_or_web_wallets',
# 'https://cointelegraph.com/news/scotcoin_project_to_support_local_organizations_and_communities',
# 'https://cointelegraph.com/news/sanctions_against_russia_getting_serious_can_bitcoin_help',
# 'https://cointelegraph.com/news/mt_gox_unable_to_make_a_surprise_out_of_the_recovery_of_200_000_btc',
# 'https://cointelegraph.com/news/cambodia_central_bank_says_bitcoin_is_not_a_currency',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_march_15_22nd',
# 'https://cointelegraph.com/news/on_wallets_and_safety_part_2_mobile_wallets',
# 'https://cointelegraph.com/news/denmark_joins_the_not_a_currency_don_t_care_club',
# 'https://cointelegraph.com/news/where_to_throw_a_bitcoin_rig_s_anchor',
# 'https://cointelegraph.com/news/bitpay_playing_monopoly',
# 'https://cointelegraph.com/news/gba_best_practice_track_at_the_bitcoin_expo_toronto',
# 'https://cointelegraph.com/news/what_you_need_to_know_about_bitcoin_core_update_0_9_0',
# 'https://cointelegraph.com/news/bitcoin_reopens_the_soul_of_a_poet',
# 'https://cointelegraph.com/news/take_my_bitcoins_from_butterfly_labs_live',
# 'https://cointelegraph.com/news/on_wallets_and_safety_part_1_desktop_wallets',
# 'https://cointelegraph.com/news/city_of_pensacola_fighting_sean_s_outpost',
# 'https://cointelegraph.com/news/bitpay_goes_beyond_26_thousand_merchants',
# 'https://cointelegraph.com/news/a_question_of_cases_bitcoin_or_bitcoin',

# 'https://cointelegraph.com/news/mastercoin_decentralizing_exchange',
# 'https://cointelegraph.com/news/central_european_bitcoin_expo_2014_to_hit_vienna_in_may',
# 'https://cointelegraph.com/news/why_you_should_bookmark_bitlegal_io',
# 'https://cointelegraph.com/news/bitcoin_expo_2014_planned_for_shanghai',
# 'https://cointelegraph.com/news/counterparty_to_set_new_standard_of_fairness_in_the_cryptographic_world',
# 'https://cointelegraph.com/news/sweet_odor_of_bitcoin_with_a_rich_citrus_note',
# 'https://cointelegraph.com/news/inside_bitcoins_conference_expo_in_new_york_city_on_april_7_8_2014',
# 'https://cointelegraph.com/news/china_s_largest_exchange_gets_10_million_thanks_to_vc_funding',
# 'https://cointelegraph.com/news/airbitz_announces_launch_of_bitcoin_business_directory',
# 'https://cointelegraph.com/news/mt_gox_website_updated_allows_users_to_check_balances',
# 'https://cointelegraph.com/news/sanctioning_by_us_and_eu_do_not_change_russia_s_determination_to_wipe_out_bitcoin',
# 'https://cointelegraph.com/news/the_relevancy_of_bitcoin_for_grass_roots',
# 'https://cointelegraph.com/news/top_7_bitcoin_related_applications_for_google_android_os',

# 'https://cointelegraph.com/news/iranian_officials_look_into_bitcoin',
# 'https://cointelegraph.com/news/hacker_attack_halts_the_work_of_poland_s_exchange',
# 'https://cointelegraph.com/news/singapore_chose_to_regulate_bitcoin_intermediaries',
# 'https://cointelegraph.com/news/altcoin_spotlight_heavycoin_goes_big_on_security',
# 'https://cointelegraph.com/news/dorian_nakamoto_refutes_newsweek_story_outing_him_as_bitcoin_creator',
# 'https://cointelegraph.com/news/distillery_in_london_accepts_bitcoin',
# 'https://cointelegraph.com/news/online_takeaway_ordering_giant_in_uk_considering_bitcoins',
# 'https://cointelegraph.com/news/interview_with_jeffrey_smith_of_ghash_io',
# 'https://cointelegraph.com/news/gocoin_proceeds_with_adding_up_altcoins_this_time_doge',

# 'https://cointelegraph.com/news/crucial_fix_for_dogecoin',
# 'https://cointelegraph.com/news/comparing_bitcoin_to_gold',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_march_8_14th',
# 'https://cointelegraph.com/news/ceo_ix_to_widen_the_list_of_services_with_ghs_future_contracts',
# 'https://cointelegraph.com/news/goldman_sachs_says_bitcoin_is_not_a_currency',
# 'https://cointelegraph.com/news/half_a_year_until_scrypt_asics_arrive',
# 'https://cointelegraph.com/news/vancouver_man_selling_woolly_mammoth_tusks_for_275_btc',
# 'https://cointelegraph.com/news/us_investigates_regulating_bitcoin_as_a_commodity',
# 'https://cointelegraph.com/news/secure_bitcoin_storage_company_raises_20_million',
# 'https://cointelegraph.com/news/big_fish_games_to_make_a_huge_catch_with_bitcoin',
# 'https://cointelegraph.com/news/from_web_kiosks_to_bitcoin_atms_in_finland',
# 'https://cointelegraph.com/news/p_j_delaney_cautious_criticism_of_renewed_bitcoin_foundation',
# 'https://cointelegraph.com/news/cloudhashing_com_announces_huge_mining_project',
# 'https://cointelegraph.com/news/perseus_telecom_launches_massive_exchange_platform',

# 'https://cointelegraph.com/news/anghami_music_streaming_went_bit',
# 'https://cointelegraph.com/news/updated_new_details_of_mt_gox_case_revealed_by_amateur_detectives',
# 'https://cointelegraph.com/news/10_worldwide_celebrities_and_their_relations_to_cryptocurrency',
# 'https://cointelegraph.com/news/luxembourg_first_to_adopt_acceptable_rules_for_bitcoin_businesses',
# 'https://cointelegraph.com/news/jeffrey_smith_of_cex_io_on_business_perspectives_and_development',
# 'https://cointelegraph.com/news/bitcoin_atm_in_ireland_facing_hurdles',
# 'https://cointelegraph.com/news/coinplug_and_nautilus_hyosung_join_forces_to_bring_two_way_atm_to_south_korea',
# 'https://cointelegraph.com/news/bitcoin_itself_may_not_last_but_the_concept_is_inevitable',
# 'https://cointelegraph.com/news/proclamations_and_leaflets_to_serve_the_peaceful_promotion_of_bitcoin',

# 'https://cointelegraph.com/news/france_initiates_revision_of_bitcoin_regulation_on_the_union_level',
# 'https://cointelegraph.com/news/ron_paul_was_demanding_legal_currency_competition_back_in_2011',
# 'https://cointelegraph.com/news/bitcoin_accepting_open_airs_and_festivals_of_2014',
# 'https://cointelegraph.com/news/egypt_s_first_bitcoin_accepting_business',
# 'https://cointelegraph.com/news/taxi_coin_to_put_the_world_on_wheels',
# 'https://cointelegraph.com/news/3_words_you_didn_t_expect_to_see_together_bitcoin_castle_estonia',
# 'https://cointelegraph.com/news/russia_to_host_its_first_bitcoin_conference',
# 'https://cointelegraph.com/news/bitcoin_decentral_accelerate_opening_windows_for_second_generation_cryptocurrencies',
# 'https://cointelegraph.com/news/circumspect_giveaway_at_the_hackathon_of_the_texas_bitcoin_conference',
# 'https://cointelegraph.com/news/wikipedia_co_founder_experimenting_with_bitcoins',
# 'https://cointelegraph.com/news/the_mt_gox_story_just_gets_uglier',
# 'https://cointelegraph.com/news/bitcoin_boulevard_will_welcome_spring_in_hague',
# 'https://cointelegraph.com/news/the_two_bit_idiot_plans_to_make_fools_of_the_bitcoin_foundation_board',
# 'https://cointelegraph.com/news/poloniex_spreads_its_bitcoin_loss_among_all_users',

# 'https://cointelegraph.com/news/bitcoin_clients_in_jeopardy_after_the_discovery_of_a_linux_bug',
# 'https://cointelegraph.com/news/is_russia_wavering_on_its_anti_bitcoin_stance',
# 'https://cointelegraph.com/news/japan_bitcoin_not_a_currency_but_taxable',
# 'https://cointelegraph.com/news/research_team_finds_a_way_to_pick_pocket_openssl_based_devices',
# 'https://cointelegraph.com/news/the_most_important_lesson_from_the_dorian_nakamoto_story',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_mar_3_7',
# 'https://cointelegraph.com/news/dorian_nakamoto_disputes_newsweek_story_says_he_s_not_satoshi_nakamoto',
# 'https://cointelegraph.com/news/ireland_installs_its_first_bitcoin_atm',
# 'https://cointelegraph.com/news/fortress_financial_group_play_big_lose_big',
# 'https://cointelegraph.com/news/amd_strikes_back_with_hbm',
# 'https://cointelegraph.com/news/london_s_first_bitcoin_machine_turns_up_in_shoreditch',
# 'https://cointelegraph.com/news/winlevii_branson_to_the_moon',
# 'https://cointelegraph.com/news/20_worth_of_btc_for_25_on_tinkercoin',
# 'https://cointelegraph.com/news/5_curious_quotes_from_newsweek_s_satoshi_nakamoto_expose',
# 'https://cointelegraph.com/news/mt_gox_source_code_too_simple_even_for_a_newbie',
# 'https://cointelegraph.com/news/buffett_bitcoin_does_not_meet_the_test_of_a_currency',
# 'https://cointelegraph.com/news/no_more_burners_freedompop_gives_you_a_fully_encrypted_phone_for_10_a_month',
# 'https://cointelegraph.com/news/bitcoin_recovers_released_from_mt_gox_bonds',
# 'https://cointelegraph.com/news/hidden_doge_mining_in_london_university',
# 'https://cointelegraph.com/news/bitcoin_exchange_bitso_endeavors_to_be_first_in_mexico',
# 'https://cointelegraph.com/news/new_statements_from_mt_gox_karpeles',
# 'https://cointelegraph.com/news/ready_or_not_here_comes_flappycoin',
# 'https://cointelegraph.com/news/micky_malka_stays_strong_as_an_iceberg_in_the_vortex_of_the_bitcoin_ocean',
# 'https://cointelegraph.com/news/clink_hostel_chain_in_london_accepting_cryptocurrencies',
# 'https://cointelegraph.com/news/bitcoin_in_ukraine_in_the_times_of_peril',
# 'https://cointelegraph.com/news/theatre_begins_with_bitcoin_in_london',

# 'https://cointelegraph.com/news/us_leading_trading_educational_platform_embraces_btc_ltc',
# 'https://cointelegraph.com/news/new_altcoin_by_gun_lovers',
# 'https://cointelegraph.com/news/toronto_bitcoin_expo_team_reveals_details_of_the_event',
# 'https://cointelegraph.com/news/first_brick_and_mortar_bitcoin_seller_opens_in_hong_kong',
# 'https://cointelegraph.com/news/erik_voorhees_had_a_busy_week_on_reddit',
# 'https://cointelegraph.com/news/buttercoin_an_exchange_backed_by_some_big_names_in_tech_announces_soft_launch',
# 'https://cointelegraph.com/news/bitcoin_technology_conference_will_hit_san_jose_in_june',
# 'https://cointelegraph.com/news/fed_says_it_cannot_regulate_bitcoin_would_rely_on_existing_legislations',
# 'https://cointelegraph.com/news/bitcoin_facts_you_might_thought_you_were_right_about',
# 'https://cointelegraph.com/news/meanwhile_in_iceland_auroracoin_price_skyrockets',
# 'https://cointelegraph.com/news/details_of_mt_gox_s_bankruptcy_protection_filing',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_feb_24_28',
# 'https://cointelegraph.com/news/new_bitcoin_exchange_from_the_founder_of_secondmarket',
# 'https://cointelegraph.com/news/one_false_move_might_have_become_fatal_for_mt_gox_and_karpeles',
# 'https://cointelegraph.com/news/indian_crypto_laxmicoin_is_held_back_by_the_rbi_raids',
# 'https://cointelegraph.com/news/180_000_hotels_for_the_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_foundation_vetting_candidates_to_replace_shrem',

# 'https://cointelegraph.com/news/microtransactions_the_future_of_online_economy',
# 'https://cointelegraph.com/news/bitcoin_atm_slated_for_a_spot_in_the_north_america_s_largest_mall',
# 'https://cointelegraph.com/news/senator_manchin_clamors_for_bitcoin_ban_in_the_usa',
# 'https://cointelegraph.com/news/lightningasic_presents_unit_for_parallel_bitcoin_and_litecoin_mining_outstripping_gridseed',
# 'https://cointelegraph.com/news/bitcoin_club_of_penn_state_university',
# 'https://cointelegraph.com/news/trojan_botnet_pony_successfully_devastates_numerous_cryptocurrency_wallets',
# 'https://cointelegraph.com/news/gks_katowice_soccer_club_accepting_bitcoin',
# 'https://cointelegraph.com/news/former_treasury_official_has_kind_words_for_bitcoin',
# 'https://cointelegraph.com/news/lottocoin_a_game_of_coin',
# 'https://cointelegraph.com/news/libertyteller_duo_manually_make_bitcoin_omnipresent',
# 'https://cointelegraph.com/news/playboy_plus_harmoniously_complements_the_list_of_bitcoin_accepting_companies',
# 'https://cointelegraph.com/news/nvidia_about_to_win_the_arms_race_against_amd',
# 'https://cointelegraph.com/news/mining_rig_are_more_expensive_on_ebay',
# 'https://cointelegraph.com/news/mt_gox_blows_fallout_could_be_catastrophic',
# 'https://cointelegraph.com/news/brick_and_mortar_portal_for_bitcoin_deposits_and_account_management_opens_in_cyprus',
# 'https://cointelegraph.com/news/ceo_mark_karpeles_resigns_while_mt_gox_covers_up_traces_in_twitter',
# 'https://cointelegraph.com/news/vietnam_forbids_bitcoin_transactions',
# 'https://cointelegraph.com/news/wima_monaco_conference',
# 'https://cointelegraph.com/news/spain_about_to_get_swamped_with_bitcoin_machines',
# 'https://cointelegraph.com/news/virtex_adds_litecoin_to_its_nomenclature',
# 'https://cointelegraph.com/news/goldman_sachs_take_on_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_only_bookmakers_platform_anonibet_guarantees_full_anonymity',
# 'https://cointelegraph.com/news/bitcoin_beauties_aim_to_tame_the_beast_of_cryptocurrency',

# 'https://cointelegraph.com/news/mt_gox_hit_the_bottom_and_is_alive_again',
# 'https://cointelegraph.com/news/winkdex_bitcoin_price_index_from_the_winklevii',
# 'https://cointelegraph.com/news/bitcoin_enthusiasts_of_ecuador_gather_up_for_the_first_time',
# 'https://cointelegraph.com/news/bitcoin_will_have_a_future_due_the_government_s_tendency_to_resemble_household',
# 'https://cointelegraph.com/news/overstock_approaching_1_million_in_bitcoin_sales',
# 'https://cointelegraph.com/news/dopamine_think_of_it_as_gpu_mining_meets_lego',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_feb_17_21',
# 'https://cointelegraph.com/news/pizza_guys_first_uae_outlet_to_embrace_bitcoin',
# 'https://cointelegraph.com/news/passportparking_opens_the_way_for_paying_bitcoin_for_a_parking_place',
# 'https://cointelegraph.com/news/tigerdirect_hooking_up_bitcoin_shoppers_with_a_20_discount',
# 'https://cointelegraph.com/news/huntercoin_earn_btc_by_playing_online_multiplayer_game',
# 'https://cointelegraph.com/news/ukraine_government_imposes_regulation_on_bitcoin',
# 'https://cointelegraph.com/news/crypto_enthusiastic_guitarists_now_have_a_place_to_spend_their_bitcoin',
# 'https://cointelegraph.com/news/techcrunch_disrupt_new_york_to_accept_bitcoin',
# 'https://cointelegraph.com/news/lamassu_beats_robocoin_to_us_market',
# 'https://cointelegraph.com/news/hungary_s_central_bank_dubs_digital_currencies_risky',
# 'https://cointelegraph.com/news/investment_boosts_the_launch_of_new_exchanger_hitbtc',

# 'https://cointelegraph.com/news/real_time_bitcoin_price_monitor',
# 'https://cointelegraph.com/news/the_way_uk_treats_bitcoin',
# 'https://cointelegraph.com/news/verso_card_storage_of_military_grade_security',
# 'https://cointelegraph.com/news/novacoin_surprises_many_makes_it_to_one_year_mark',
# 'https://cointelegraph.com/news/brick_and_mortar_bitcoin_shop_opens_in_london',
# 'https://cointelegraph.com/news/wedbush_securities_a_pioneer_in_accepting_bitcoin',
# 'https://cointelegraph.com/news/ceo_of_laureate_trust_bitcoin_is_stable_and_will_continue_to_rise',

# 'https://cointelegraph.com/news/what_future_awaits_bitcoin_exchanges',
# 'https://cointelegraph.com/news/bitcoin_is_not_a_closed_book_anymore',
# 'https://cointelegraph.com/news/two_us_retailers_that_are_actually_holding_on_to_their_bitcoins',
# 'https://cointelegraph.com/news/first_american_bitcoin_atms_coming_to_seattle_and_austin',
# 'https://cointelegraph.com/news/mt_gox_announces_timeline_for_resuming_withdrawals',
# 'https://cointelegraph.com/news/uae_does_not_see_bitcoin_as_trustworthy',
				
# 'https://cointelegraph.com/news/colony_earth_a_society_built_on_bitcoin',
# 'https://cointelegraph.com/news/hackers_hit_silk_road_2_hard',
# 'https://cointelegraph.com/news/bitcoinwarrior_arranges_internet_community_to_fight_for_their_freedoms',
# 'https://cointelegraph.com/news/techcrunch_readers_vote_bitcoin_best_technology_achievement',
# 'https://cointelegraph.com/news/ipad_point_of_sale_maker_introduces_bitcoin_payments',
# 'https://cointelegraph.com/news/20_withholding_italy_announces_capital_controls_on_incoming_foreign_transfers',
# 'https://cointelegraph.com/news/london_to_host_digital_money_event_in_may',
# 'https://cointelegraph.com/news/white_house_gives_guidelines_regarding_cybersecurity',
# 'https://cointelegraph.com/news/itireleng_promotes_bitcoin_in_botswana',
				
# 'https://cointelegraph.com/news/is_there_a_solution_for_bitcoin_volatile_nature',
# 'https://cointelegraph.com/news/bitcoin_statement_populated_by_the_bank_of_greece',
# 'https://cointelegraph.com/news/bitcoin_trading_resumes_in_thailand_after_government_alters_its_stance',
# 'https://cointelegraph.com/news/send_flowers_speculate_on_tulip_prices_with_bitcoin',
# 'https://cointelegraph.com/news/money2020_conference_planning_to_spotlight_bitcoin_this_year',
# 'https://cointelegraph.com/news/andreas_antonopolous_on_having_to_defend_bitcoin_on_bloomberg',
# 'https://cointelegraph.com/news/are_you_a_btc_millionaire',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_feb_10_14',
# 'https://cointelegraph.com/news/speculations_on_bitcoin_platform_for_customers_proved_false',
# 'https://cointelegraph.com/news/florida_charges_localbitcoins_com_users',
# 'https://cointelegraph.com/news/porn_and_bitcoin_it_s_time_for_a_serious_discussion',
# 'https://cointelegraph.com/news/how_to_buy_from_major_american_retailers_with_bitcoin',

# 'https://cointelegraph.com/news/highkart_com_available_only_for_btc',
# 'https://cointelegraph.com/news/music_from_transactions_and_malware',
# 'https://cointelegraph.com/news/cryptsy_com_have_begun_to_trade_devcoin_for_bitcoin',
# 'https://cointelegraph.com/news/someone_leaked_eu_proposals_to_redistribute_wealth_from_personal_savings_accounts',
# 'https://cointelegraph.com/news/guernsey_takes_an_official_position_on_digital_currencies',
# 'https://cointelegraph.com/news/bitcoin_trades_under_complex_ddos_attack',
# 'https://cointelegraph.com/news/local_currencies_too_alternative_even_for_bitcoin',
# 'https://cointelegraph.com/news/lithuania_clarifies_stance_on_cryptocurrencies',
# 'https://cointelegraph.com/news/central_bank_of_cyprus_disapproves_of_cryptocurrencies',
# 'https://cointelegraph.com/news/agonizing_mt_gox_blames_bitcoin_for_insolvency',
# 'https://cointelegraph.com/news/bus_tickets_in_canberra_can_be_purchased_with_bitcoin',
# 'https://cointelegraph.com/news/the_nsa_was_investigating_cryptocurrencies_in_1996',
# 'https://cointelegraph.com/news/bitcoin_penny_stocks_bitcoin_shop_inc_goes_public',
# 'https://cointelegraph.com/news/law_coryphaeus_sheridans_to_accept_bitcoin',
# 'https://cointelegraph.com/news/native_american_tribe_decides_to_adapt_crypto',

# 'https://cointelegraph.com/news/solarcoin_to_bring_it_progress_and_environmental_protection_together',
# 'https://cointelegraph.com/news/altcoin_spotlight_iceland_s_auroracoin',
# 'https://cointelegraph.com/news/virgin_galactic_already_has_six_bitcoin_customers',
# 'https://cointelegraph.com/news/ross_ulbricht_pleads_not_guilty_on_all_charges',
# 'https://cointelegraph.com/news/max_keiser_establishes_own_alternative_currency',
# 'https://cointelegraph.com/news/4_in_5_american_consumers_would_never_consider_using_digital_currency',
# 'https://cointelegraph.com/news/chaos_computer_club_versus_german_government',
# 'https://cointelegraph.com/news/big_time_telecoms_provider_accepting_bitcoin',
# 'https://cointelegraph.com/news/survey_on_bitcoin_detects_mistrust_in_cryptocurrencies',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_feb_3_7',
# 'https://cointelegraph.com/news/it_s_time_to_take_dogecoin_seriously',
				
# 'https://cointelegraph.com/news/smart_wristband_holds_digital_coins',
# 'https://cointelegraph.com/news/smart_price_tags_for_bitcoin',
# 'https://cointelegraph.com/news/apple_pulls_blockchain_info_wallet_app_bitcoin_community_responds',
# 'https://cointelegraph.com/news/kazakhstan_to_determine_position_on_bitcoin_in_2014',
# 'https://cointelegraph.com/news/ultracoin_index_software_to_determine_risks_and_opportunities_of_cryptocoins',
# 'https://cointelegraph.com/news/winklevoss_twins_to_become_authorized_etf_investors',
# 'https://cointelegraph.com/news/bitcoin_atms_are_invading_australia',
# 'https://cointelegraph.com/news/dogecoin_funded_jamaican_bobsled_team_recovers_lost_equipment',
# 'https://cointelegraph.com/news/bitcoin_inspires_tattoo_art',
# 'https://cointelegraph.com/news/cheapair_com_book_a_hotel_room_in_bitcoin',
# 'https://cointelegraph.com/news/private_jet_company_books_first_bitcoin_customer',
				
# 'https://cointelegraph.com/news/first_graphic_novel_bought_with_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_voyage_on_a_luxury_yacht',
# 'https://cointelegraph.com/news/us_postal_service_willing_to_provide_bitcoin_exchange',
# 'https://cointelegraph.com/news/bitcoin_atm_coming_to_singapore_in_march',
# 'https://cointelegraph.com/news/elliptic_vault_craves_for_credence_before_developing_new_solutions',
# 'https://cointelegraph.com/news/exchanges_open_in_france_would_require_registration',
# 'https://cointelegraph.com/news/arcade_machines_now_accept_digital_coins',
# 'https://cointelegraph.com/news/human_factor_to_determine_the_operation_of_bitcoin_atm',
# 'https://cointelegraph.com/news/the_gentle_scent_of_bitcoin',
# 'https://cointelegraph.com/news/finding_a_way_in_the_bitcoin_labyrinth',
# 'https://cointelegraph.com/news/argentines_demand_us_dollars_but_don_t_trust_nation_s_banks_for_safekeeping',
# 'https://cointelegraph.com/news/beachfront_apartments_for_sale_in_cyprus_bitcoin_gladly_accepted',
# 'https://cointelegraph.com/news/silk_road_seller_claims_innocence_plans_to_sue_us_for_seized_bitcoins',
# 'https://cointelegraph.com/news/hong_kong_based_exchange_secures_2_million_investment',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_jan_27_31',
# 'https://cointelegraph.com/news/btc_china_begins_to_accept_yuan_again',
# 'https://cointelegraph.com/news/s_e_b_rejects_bitcoin',
# 'https://cointelegraph.com/news/bay_area_car_dealer_sells_land_rover_for_bitcoin',
# 'https://cointelegraph.com/news/cryptocurrencies_a_cyber_threat_or_panders_of_terrorism',
# 'https://cointelegraph.com/news/estonian_central_bank_bitcoin_could_just_be_a_ponzi_scheme',
# 'https://cointelegraph.com/news/major_update_to_the_vault_of_satoshi',
# 'https://cointelegraph.com/news/vera_john_casino_to_include_bitcoin_in_the_range_of_payment_methods',
# 'https://cointelegraph.com/news/back_to_future_how_often_bitcoin_is_going_to_rise_from_ashes',
# 'https://cointelegraph.com/news/microsoft_approves_new_trading_features_of_kraken_application',
# 'https://cointelegraph.com/news/andreas_antonopolous_sums_up_perfectly_what_the_nycfds_hearing_completely_misses',
# 'https://cointelegraph.com/news/shrem_and_hsbc_a_tale_of_two_money_laundering_cases',
# 'https://cointelegraph.com/news/coinbase_revised_its_policy_on_limits_and_denominations',
# 'https://cointelegraph.com/news/litecoin_knacks_a_problem_unsolved_by_authorities_of_madagascar',
# 'https://cointelegraph.com/news/video_card_retailer_appreciates_selling_boom_after_accepting_bitcoin',

# 'https://cointelegraph.com/news/digital_currency_from_russia',
# 'https://cointelegraph.com/news/highlights_andreas_antonopolous_on_the_joe_rogan_experience_podcast',
# 'https://cointelegraph.com/news/the_wolfs_from_wall_street_show_vigorous_interest_in_bitcoin',
# 'https://cointelegraph.com/news/after_arrest_charlie_shrem_resigns_from_post_at_bitcoin_foundation',
# 'https://cointelegraph.com/news/bitcoin_inspires_developers_to_create_a_delocalized_internet',
# 'https://cointelegraph.com/news/the_central_bank_of_russia_aims_to_protect_citizenry_from_bitcoin',
				
# 'https://cointelegraph.com/news/cryptocurrencies_introduced_to_the_definition_of_money_by_washington_dpi',
# 'https://cointelegraph.com/news/the_official_statement_of_russia_on_cryptographic_currencies',
# 'https://cointelegraph.com/news/the_official_reactions_on_the_arresting_of_bitinstant_ceo_charlie_shrem',
# 'https://cointelegraph.com/news/bitcoin_community_reacts_to_charlie_shrem_s_arrest',
# 'https://cointelegraph.com/news/ceo_of_bitintstant_arrested_charged_with_conspiring_to_launder_money_on_silk_road',
				
# 'https://cointelegraph.com/news/bitcloud_global_network_based_on_cryptocoins',
# 'https://cointelegraph.com/news/new_bitcoin_exchange_service_is_going_to_predetermine_the_distribution_of_forces',
# 'https://cointelegraph.com/news/prague_is_about_to_get_a_bitcoin_atm',
# 'https://cointelegraph.com/news/swedish_tax_official_bitcoin_likely_to_be_regulated_as_asset',
# 'https://cointelegraph.com/news/earthcoin_cryptocurrency_with_vision_and_ambition',
# 'https://cointelegraph.com/news/the_perspectives_of_bitcoin_in_africa',
# 'https://cointelegraph.com/news/connie_gallipi_proves_that_bitcoin_might_change_the_course_of_life',
# 'https://cointelegraph.com/news/marc_andreessen_makes_the_case_for_bitcoin_in_the_new_york_times',
# 'https://cointelegraph.com/news/bitcoin_comes_to_las_vegas',
# 'https://cointelegraph.com/news/texas_congressman_one_of_bitcoin_s_biggest_supporters_in_washington',
# 'https://cointelegraph.com/news/gold_and_diamond_jewelers_in_us_can_expect_bitcoin_payment_processors_soon',

# 'https://cointelegraph.com/news/voting_system_based_on_bitcoin_to_be_developed',
# 'https://cointelegraph.com/news/creator_of_ripple_donates_a_half_million_dollars_for_ai_research',
# 'https://cointelegraph.com/news/steve_stockman_on_freedom_bitcoin_and_future_of_the_country',
# 'https://cointelegraph.com/news/bit4coin_reviews_on_success_after_1000_sold_gift_cards_to_develop_new_ideas',
# 'https://cointelegraph.com/news/bringing_bitcoin_closer_to_hard_cash_in_italy',
# 'https://cointelegraph.com/news/petition_to_get_amazon_to_accept_bitcoin_on_change_org',
# 'https://cointelegraph.com/news/financial_forecasting_firm_accepting_bitcoins',
# 'https://cointelegraph.com/news/israel_chooses_to_observe_and_report',
# 'https://cointelegraph.com/news/ebay_to_change_policy_on_bitcon_from_10th_february',
# 'https://cointelegraph.com/news/dogecoins_pouring_in_for_jamaican_bobsled_team',
# 'https://cointelegraph.com/news/satoshi_square_held_in_london_for_the_first_time',
# 'https://cointelegraph.com/news/the_economist_catches_readers_up_on_quantitative_easing',
# 'https://cointelegraph.com/news/the_scientific_explanation_of_the_bitcoin_attractiveness',
# 'https://cointelegraph.com/news/wedbush_securities_analyst_about_bitcoin',
# 'https://cointelegraph.com/news/altcoin_spotlight_franko',
# 'https://cointelegraph.com/news/bitcoin_donations_factoring_into_romanian_presidential_campaign',
# 'https://cointelegraph.com/news/goodbye_coinye_kanye_west_cleanses_the_alternative_currencies_environment',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_jan_12_18',
# 'https://cointelegraph.com/news/ron_paul_talks_about_ronpaulcoin_cryptocurrencies',

# 'https://cointelegraph.com/news/nba_team_sacramento_kings_embraces_bitcoin',
# 'https://cointelegraph.com/news/rural_english_farm_to_be_booked_out_for_events',
# 'https://cointelegraph.com/news/bitcoin_a_topic_of_discussion_on_asian_financial_forum',
# 'https://cointelegraph.com/news/zerocoin_unable_to_merge_with_bitcoin_goes_independent',
# 'https://cointelegraph.com/news/blockchain_info_s_grand_prize_goes_to_a_teenager',
# 'https://cointelegraph.com/news/butterfly_labs_complete_backlogs_with_a_beck_of_wing',
# 'https://cointelegraph.com/news/bitcoins_are_enough_to_provide_bad_and_breakfast',
# 'https://cointelegraph.com/news/online_eyewear_retailer_coastal_accepting_bitcoins',
# 'https://cointelegraph.com/news/bitcoin_joins_the_cohort_of_precious_metals_as_long_time_investment_option',
# 'https://cointelegraph.com/news/french_legislators_hold_hearing_on_bitcoin',
# 'https://cointelegraph.com/news/chicago_sun_times_checking_out_pay_to_read',
				
# 'https://cointelegraph.com/news/educative_coinscrum_bitcoin_business_networking_event_will_shake_london',
# 'https://cointelegraph.com/news/irish_parliamentarian_seeks_to_investigate_bitcoin',
# 'https://cointelegraph.com/news/complex_retail_system_accepts_bitcoin',
# 'https://cointelegraph.com/news/asset_trading_platform_opens_up_to_bitcoin',
# 'https://cointelegraph.com/news/uk_s_no_1_flight_school_accepting_bitcoins',
# 'https://cointelegraph.com/news/two_beer_or_not_two_beer_the_question_is_for_bitcoin',
# 'https://cointelegraph.com/news/identified_digital_currency_from_planet_earth',
# 'https://cointelegraph.com/news/lemonade_stand_offers_refreshments_cookies_and_adorable_smiles_for_bitcoins',
# 'https://cointelegraph.com/news/bitcoin_capable_to_satisfy_the_primary_needs_of_humans',
# 'https://cointelegraph.com/news/gocoin_begins_to_accept_litecoin',
# 'https://cointelegraph.com/news/richard_branson_why_virgin_galactic_would_accept_bitcoins',
# 'https://cointelegraph.com/news/charter_your_next_private_flight_with_bitcoins',
# 'https://cointelegraph.com/news/faster_mining_with_polish_innovation_bi_fury_5gh_usb_asic',

# 'https://cointelegraph.com/news/buybitcoin_ph_the_newest_bitcoin_exchange_in_the_philippines',
# 'https://cointelegraph.com/news/big_plans_from_the_sean_s_outpost_charity',
# 'https://cointelegraph.com/news/irs_give_u_s_taxpayers_their_law',
# 'https://cointelegraph.com/news/bitcoin_legal_status_mirrored_on_a_political_map_while_being_called_speculative',
# 'https://cointelegraph.com/news/two_horse_race_of_2014_or_bitcoin_against_western_union',
# 'https://cointelegraph.com/news/review_the_image_of_kipochi_after_6_months_of_operation',
# 'https://cointelegraph.com/news/bitcoin_at_your_fingerprints',
# 'https://cointelegraph.com/news/1_in_50_orders_on_pizza_be_paid_for_in_bitcoin',
# 'https://cointelegraph.com/news/the_centralization_of_mining_and_the_threat_of_a_51_attack',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_jan_1_11',
# 'https://cointelegraph.com/news/chilean_entertainment_venue_to_be_the_foremost_bitcoin_ambassador_in_the_country',

# 'https://cointelegraph.com/news/winery_to_pay_with_bitcoin_this_time_new_zealand',
# 'https://cointelegraph.com/news/overstock_already_accepting_bitcoins',
# 'https://cointelegraph.com/news/seoul_hair_salon_accepting_bitcoin_payments',
# 'https://cointelegraph.com/news/winery_to_pay_with_bitcoin_this_time_new_zealand',
# 'https://cointelegraph.com/news/lily_allen_gave_away_the_opportunity_to_become_a_bitcoin_millionaire',
# 'https://cointelegraph.com/news/yahoo_spreads_bitcoin_malware_to_2_million_users',
# 'https://cointelegraph.com/news/time_and_date_set_for_the_north_american_bitcoin_conference',

# 'https://cointelegraph.com/news/the_botswana_don_quixote_in_fight_for_bitcoin_recognition',
# 'https://cointelegraph.com/news/india_commerce_ministry_investigating_tea_sold_for_btc',
# 'https://cointelegraph.com/news/tipping_your_way_through_tweets',
# 'https://cointelegraph.com/news/open_collaboration_as_parent_of_bitcoin_to_change_the_future_economy',
# 'https://cointelegraph.com/news/several_alternative_currencies_thriving_in_the_netherlands',
# 'https://cointelegraph.com/news/place_for_your_ad_on_facebook_for_bitcoin',

# 'https://cointelegraph.com/news/janet_yellen_was_elected_to_be_the_chair_of_the_fed',
# 'https://cointelegraph.com/news/hashfast_customers_might_take_company_to_court',
# 'https://cointelegraph.com/news/bitcoin_security_for_newbies',
# 'https://cointelegraph.com/news/dutch_service_bitplaats_offers_services_to_belgian_customers',
# 'https://cointelegraph.com/news/scientist_raising_bitcoins_for_cancer_research',

# 'https://cointelegraph.com/news/bitpos_launched_in_australia_to_turn_soon_into_a_secret_project',
# 'https://cointelegraph.com/news/robocoin_looks_to_ship_45_atms_by_spring_updated',
# 'https://cointelegraph.com/news/digging_for_bitcoins_in_real_world',
# 'https://cointelegraph.com/news/nxt_the_next_step_in_the_development_of_cryptocurrencies',
# 'https://cointelegraph.com/news/bitcoin_payments_are_gaining_momentum_on_mobile_nations',
# 'https://cointelegraph.com/news/chinese_sina_corporation_launched_a_bitcoin_statistics_platform',
# 'https://cointelegraph.com/news/bitcoin_crosses_1_000_threshold_once_again',
# 'https://cointelegraph.com/news/your_money_s_security_bitcoin_vs_credit_cards',
# 'https://cointelegraph.com/news/malaysia_joins_singapore_in_hands_off_policy_on_bitcoin',

# 'https://cointelegraph.com/news/how_far_will_lead_the_invention_of_new_cryptocurrencies',
# 'https://cointelegraph.com/news/happy_5th_birthday_genesis_block',
# 'https://cointelegraph.com/news/hair_clinics_in_london_spain_dubai_and_brazil_accepting_bitcoins',
# 'https://cointelegraph.com/news/bitcoin_network_decorated_with_celtic_knotwork',
# 'https://cointelegraph.com/news/zynga_playing_around_with_bitcoin',

# 'https://cointelegraph.com/news/not_all_bitcoins_go_to_heaven',
# 'https://cointelegraph.com/news/tropical_paradise_available_for_bitcoin',
# 'https://cointelegraph.com/news/theater_company_in_texas_capital_accepting_bitcoins',

# 'https://cointelegraph.com/news/bitcoin_center_has_been_opened_in_new_york',
# 'https://cointelegraph.com/news/lebanese_central_bank_issues_middle_east_s_first_bitcoin_warning',
# 'https://cointelegraph.com/news/37coins_to_make_bitcoin_transactions_simpler',
# 'https://cointelegraph.com/news/password_anonymity_provided_for_bitcoin_by_clipperz',
# 'https://cointelegraph.com/news/car_listings_site_targeting_bitcoin_users_in_the_uk',

# 'https://cointelegraph.com/news/blockchain_info_to_support_elsa_hammond_in_the_raw_for_pacific',
# 'https://cointelegraph.com/news/us_soccer_association_accepting_bitcoins',
# 'https://cointelegraph.com/news/investor_chris_dixon_why_i_am_interested_in_bitcoin',
# 'https://cointelegraph.com/news/canadians_are_bullish_on_adopting_digital_wallets',
# 'https://cointelegraph.com/news/check_out_this_prototype_bitcoin_validator_for_vending_machines',
# 'https://cointelegraph.com/news/5_best_cities_for_bitcoin_users_in_america',
# 'https://cointelegraph.com/news/lamassu_sells_its_100th_bitcoin_atm',
# 'https://cointelegraph.com/news/the_coin_telegraph_annual_review',
# 'https://cointelegraph.com/news/globalpost_names_bitcoin_currency_of_the_year',
# 'https://cointelegraph.com/news/fincen_not_requiring_individual_bitcoin_miners_to_register',
# 'https://cointelegraph.com/news/coming_soon_seasteads_libertarian_havens_in_international_waters',
# 'https://cointelegraph.com/news/new_york_property_advertising_for_bitcoins',
# 'https://cointelegraph.com/news/so_scrooge_hackers_steal_millions_of_dogecoins_on_christmas',
# 'https://cointelegraph.com/news/goldman_sachs_board_member_to_join_circle_s_board',
# 'https://cointelegraph.com/news/green_bitcoin_mining_without_leaving_home',
# 'https://cointelegraph.com/news/indian_government_raids_local_bitcoin_exchange',
# 'https://cointelegraph.com/news/litecoin_gets_its_own_widget_on_at_forexminute',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_dec_20_27',
# 'https://cointelegraph.com/news/iceland_the_land_of_geothermal_energy_and_bitcoin_mines',
# 'https://cointelegraph.com/news/seedcoin_seeking_to_incubate_bitcoin_startups',
# 'https://cointelegraph.com/news/entrepreneurs_you_should_start_accepting_bitcoin_in_2014',
# 'https://cointelegraph.com/news/india_softens_the_attitude_towards_bitcoin_by_launching_new_exchange_service',
# 'https://cointelegraph.com/news/you_can_buy_a_personal_aircraft_with_your_bitcoins',
# 'https://cointelegraph.com/news/slovenia_clears_up_how_it_might_tax_digital_currencies',

# 'https://cointelegraph.com/news/interest_and_positive_attitude_towards_bitcoin_proven_by_bank_of_japan',
# 'https://cointelegraph.com/news/bitcoin_started_to_ensure_healthcare_for_its_owners_in_2013',
# 'https://cointelegraph.com/news/obamacoin_change_we_can_believe_in',
# 'https://cointelegraph.com/news/singapore_government_adopting_hands_off_approach_to_bitcoin',
# 'https://cointelegraph.com/news/seals_with_clubs_unable_to_secure_thousands_of_user_passwords',
# 'https://cointelegraph.com/news/bitcoin_announcement_examining_the_overstock_com',
# 'https://cointelegraph.com/news/indonesia_s_fledgling_bitcoin_scene',
# 'https://cointelegraph.com/news/polish_ministry_of_finance_we_are_not_blocking_bitcoin_development',
# 'https://cointelegraph.com/news/bitcoin_gift_card_definitely_the_best_present_for_christmas',
# 'https://cointelegraph.com/news/vancouver_bitcoin_exchange_supplier_raises_525k',
# 'https://cointelegraph.com/news/bitcoin_the_official_currency_of_the_patch_autonomy',
# 'https://cointelegraph.com/news/wooden_bitcoin_wallets_are_hard_to_break',
# 'https://cointelegraph.com/news/bitcoin_is_a_movie_star_along_robots_and_cyborgs',
# 'https://cointelegraph.com/news/three_good_options_for_blowing_your_bitcoin_wealth',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_dec_13_20',
# 'https://cointelegraph.com/news/an_effective_breaking_open_of_telegram_protocol_is_200_000_worth',

# 'https://cointelegraph.com/news/the_exchange_service_mt_gox_to_enter_the_2014_with_new_features',
# 'https://cointelegraph.com/news/bitcoin_holiday_shopping_your_guide_to_last_minute_gifts',
# 'https://cointelegraph.com/news/heineken_teases_followers_about_bitcoin_payments',
# 'https://cointelegraph.com/news/finland_gets_its_first_bitcoin_atm',
# 'https://cointelegraph.com/news/ibm_is_ready_to_create_a_platform_for_tracking_of_virtual_currencies',
# 'https://cointelegraph.com/news/two_bits_are_creating_a_link_the_coin_enters_the_torrent_world',
# 'https://cointelegraph.com/news/fincen_making_attempts_to_regulate_the_bitcoin_environment_in_the_usa',
# 'https://cointelegraph.com/news/denmark_has_presented_its_attitude_on_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_trademark_has_found_a_new_owner_in_russia',
# 'https://cointelegraph.com/news/naive_owners_of_mac_os_loose_data_because_of_greed',
# 'https://cointelegraph.com/news/wow_so_profit_an_introduction_to_dogecoin',
# 'https://cointelegraph.com/news/aggressively_marketed_russian_bar_accepting_bitcoins',
# 'https://cointelegraph.com/news/china_continues_the_strife_with_bitcoin_harming_the_crypto_environment',
# 'https://cointelegraph.com/news/bitcoin_gets_registration_being_paid_for_real_estate_properties',
# 'https://cointelegraph.com/news/lifelock_acquires_lemon_wallet',
# 'https://cointelegraph.com/news/bitcoin_prices_more_volatile_on_mt_gox_exchange',
# 'https://cointelegraph.com/news/next_year_s_marketing_tendencies_and_is_bitcoin_aboard',
# 'https://cointelegraph.com/news/a_steep_patch_of_a_bitcoin_exchange_service_bit121_to_bank_deposits_in_the_uk',
# 'https://cointelegraph.com/news/the_inherent_limitations_of_bitcoin',
# 'https://cointelegraph.com/news/litecoin_mining_radeon_gpu_shortage_reported',
# 'https://cointelegraph.com/news/scandinavian_pizza_delivery_service_accepts_bitcoins_in_three_countries',
# 'https://cointelegraph.com/news/first_taiwan_bitcoin_exchange_coming_in_january',
# 'https://cointelegraph.com/news/russia_acknowledges_crypto_currencies_endorsing_bitcoin',
# 'https://cointelegraph.com/news/we_don_t_need_no_education_we_provide_it_ourselves',
# 'https://cointelegraph.com/news/inside_bitcoin_day_2_11th_december',
# 'https://cointelegraph.com/news/58_of_americans_do_not_know_what_bitcoin_is',
# 'https://cointelegraph.com/news/norway_deems_bitcoin_a_taxable_asset_not_a_currency',
# 'https://cointelegraph.com/news/numismatics_of_the_cyber_world_or_who_was_left_behind_by_bitcoin',
# 'https://cointelegraph.com/news/what_to_know_about_the_bitcoin_0_8_6_update',
# 'https://cointelegraph.com/news/how_much_antipode_is_the_attitude_of_australia_on_bitcoin',
# 'https://cointelegraph.com/news/eba_to_warn_the_population_of_europe_on_cryptocurrencies',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_dec_7_13',
# 'https://cointelegraph.com/news/on_coinbase_s_big_december',
# 'https://cointelegraph.com/news/baltimore_bar_beckons_bitcoin_beer_buyers',
# 'https://cointelegraph.com/news/bitpay_passes_a_new_milestone_looking_forward_to_new_records',
# 'https://cointelegraph.com/news/bitcoin_flying_in_dreams_and_reality_or_how_recession_was_provoked',
# 'https://cointelegraph.com/news/bitcoin_giveaway_helps_to_advertise_the_crypto_currency_on_twitter',
# 'https://cointelegraph.com/news/bitcoin_oligarchs_47_people_own_more_than_a_quarter_of_all_bitcoins',
# 'https://cointelegraph.com/news/bitcoin_making_waves_in_the_music_industry',
# 'https://cointelegraph.com/news/paypal_president_marcus_in_favor_of_bitcoin_not_nfc',
# 'https://cointelegraph.com/news/counting_sheep_really_makes_one_want_to_sleep',
# 'https://cointelegraph.com/news/changing_the_angle_of_sight_of_crowdfunding_in_the_bitcoin_environment',
# 'https://cointelegraph.com/news/kazakhstan_bitcoin_may_threaten_country_s_economic_stability',
# 'https://cointelegraph.com/news/sweden_s_first_bitcoin_atm_finds_a_home',
# 'https://cointelegraph.com/news/mt_gox_partnership_will_help_some_of_its_latin_american_customers',
# 'https://cointelegraph.com/news/easycoin_to_bypass_banks_to_ensure_more_comfortable_operation',

# 'https://cointelegraph.com/news/ebay_requests_a_physical_guarantee_to_allow_selling_bitcoins',
# 'https://cointelegraph.com/news/no_sacred_status_for_bitcoin_in_india',
# 'https://cointelegraph.com/news/on_her_majesty_s_public_service_bitcoin',
# 'https://cointelegraph.com/news/btc_in_the_lbc_buy_snoop_s_new_record_in_bitcoin',
# 'https://cointelegraph.com/news/swiss_parliament_mulling_over_bitcoin_as_foreign_currency',
# 'https://cointelegraph.com/news/how_to_keep_your_bitcoins_secure_hint_not_in_online_wallets',
# 'https://cointelegraph.com/news/buy_street_burgers_in_london_with_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_plunges_again_as_baidu_and_china_telecom_drop_the_currency',
# 'https://cointelegraph.com/news/lithuanian_orthopedic_clinic_accepting_bitcoin_payments',
# 'https://cointelegraph.com/news/bank_expects_the_bitcoin_price_to_stabilize_at_1300',
# 'https://cointelegraph.com/news/bitcoin_a_boon_to_auto_dealers',
# 'https://cointelegraph.com/news/developer_looking_to_outer_space_to_secure_bitcoin_network',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_december_1',
# 'https://cointelegraph.com/news/optimism_and_pessimism_regarding_china_s_classification_of_bitcoin',
# 'https://cointelegraph.com/news/innovations_in_donations_the_promise_of_bitcoin',
# 'https://cointelegraph.com/news/fast_bitcoin_transactions_with_mobile_payment_apps',
# 'https://cointelegraph.com/news/bitcoin_salaries_becoming_more_attractive',
# 'https://cointelegraph.com/news/new_bitcoin_transaction_points_coming_to_europe',
# 'https://cointelegraph.com/news/bitcoin_mobile_currency_for_versatile_people_preferring_agile_cars',
# 'https://cointelegraph.com/news/bitcoin_jesus_and_the_largest_bitcoin_donation',
# 'https://cointelegraph.com/news/bitcoin_s_status_in_germany',
# 'https://cointelegraph.com/news/entertainment_capital_of_the_world_to_host_inside_bitcoins_conference_next_week',
# 'https://cointelegraph.com/news/bitcoin_popularity_draws_attention_to_the_personality_of_satoshi_nakamoto',
# 'https://cointelegraph.com/news/3_bitcoin_innovations_to_keep_an_eye_on',
# 'https://cointelegraph.com/news/a_different_perspective_experts_speculate_on_bitcoin_s_future',
# 'https://cointelegraph.com/news/how_difficult_is_to_hide_a_black_in_sheep_in_a_white_flock',
# 'https://cointelegraph.com/news/cryptolocker_allowing_users_to_pay_extra_for_overdue_ransom',
# 'https://cointelegraph.com/news/yourfreeproxy_secretly_mining_bitcoins_on_users_computers',
# 'https://cointelegraph.com/news/hackers_attack_bitcoin_talk_forum_once_again',
# 'https://cointelegraph.com/news/can_uk_bank_protocols_protect_bitcoin_users',
# 'https://cointelegraph.com/news/btc_china_attempting_to_legalize_and_obtain_official_status_for_bitcoin',
# 'https://cointelegraph.com/news/a_look_inside_asicminer_s_cooling_plant',
# 'https://cointelegraph.com/news/bitcoin_on_the_top_of_the_world_what_s_next',
# 'https://cointelegraph.com/news/outstanding_idea_of_a_young_student_brought_24_380',
# 'https://cointelegraph.com/news/activist_seeking_true_anonymity_from_bitcoin',

# 'https://cointelegraph.com/news/joke_hits_the_price_of_bitcoin_and_avalanches_the_market',
# 'https://cointelegraph.com/news/treasure_island_alderney_to_become_the_heart_of_the_bitcoin_world',
# 'https://cointelegraph.com/news/aussies_coinjar_standing_tall_after_a_major_investment',
# 'https://cointelegraph.com/news/leaked_documents_explaining_rabobank_blocking_bitcoin_related_trades',
# 'https://cointelegraph.com/news/november_review',
# 'https://cointelegraph.com/news/coinmap_popularity_growth',
# 'https://cointelegraph.com/news/it_gets_really_hot_1_000_for_bitcoin',
# 'https://cointelegraph.com/news/litecoin_takes_a_chance',
# 'https://cointelegraph.com/news/7500_btc_hidden_in_a_dump',
# 'https://cointelegraph.com/news/bracelets_worth_bitcoin_or_how_to_be_a_professional_millionaire',
# 'https://cointelegraph.com/news/zeroblock_for_everyone',
# 'https://cointelegraph.com/news/bitcoin_as_alternative_for_the_traditional_currencies_p_p_part_2_the_current_situation',
# 'https://cointelegraph.com/news/data_storage_can_now_be_paid_with_bitcoins',
# 'https://cointelegraph.com/news/every_little_bit_counts_in_conscious_cookery_san_diego',
# 'https://cointelegraph.com/news/kncminer_starts_a_new_bitcoin_miner_offer_for_retail',
# 'https://cointelegraph.com/news/plug_and_play_expo_2013_to_promote_bitcoin_startups',
# 'https://cointelegraph.com/news/city_wine_cellar_success_story',
# 'https://cointelegraph.com/news/coinsetter_ready_to_complete_an_investment_round',
# 'https://cointelegraph.com/news/polish_dentist_accepts_bitcoin',
# 'https://cointelegraph.com/news/gyft_s_target_gift_cards_for_the_target_corporation',
# 'https://cointelegraph.com/news/china_s_view_on_bitcoin',
# 'https://cointelegraph.com/news/bips_attacked_1_million_dollars_missing',
# 'https://cointelegraph.com/news/bitcoin_as_alternative_for_the_traditional_currencies_p_p_part_1_the_current_situation',
# 'https://cointelegraph.com/news/bitcoin_robbery_or_how_thieves_have_stolen_a_wallet_from_a_digital_pocket',
# 'https://cointelegraph.com/news/bitcoin_image_speaking_in_plain_words',
# 'https://cointelegraph.com/news/the_btc_sx_exceeds_13_5_million_dollars_in_trafficking',
# 'https://cointelegraph.com/news/black_friday_enters_bitcoin_community_with_special_offers',
# 'https://cointelegraph.com/news/sean_s_outpost_to_open_new_horizons_of_charity_with_bitcoin',
# 'https://cointelegraph.com/news/what_does_silks_road_and_satoshi_nakamoto_have_in_common',
# 'https://cointelegraph.com/news/new_competitor_for_the_bitcoin_goldcoin',
# 'https://cointelegraph.com/news/rate_of_interest_for_bitcoins_rises_on_the_forex_market',
# 'https://cointelegraph.com/news/renminbi_meeting_bitcoin_in_beijing',
# 'https://cointelegraph.com/news/amazon_virtual_currency_is_now_available_for_uk_kindle_owners',
# 'https://cointelegraph.com/news/mysterious_transaction_of_194_993_btc',
# 'https://cointelegraph.com/news/first_aid_to_bitcoin_brokers_on_the_web',
# 'https://cointelegraph.com/news/bitcoin_future_in_canada',
# 'https://cointelegraph.com/news/buy_your_space_flight_with_bitcoin',
# 'https://cointelegraph.com/news/cryptoauction_instead_of_ebay',
# 'https://cointelegraph.com/news/official_statement_of_the_representative_of_the_china_central_bank_on_bitcoin',
# 'https://cointelegraph.com/news/silk_road_story_to_go_on_the_white_screen',
# 'https://cointelegraph.com/news/a_tough_problem_presents_new_horizons_for_solutions',
# 'https://cointelegraph.com/news/bitcoin_marching_enters_washington',
# 'https://cointelegraph.com/news/based_in_the_netherlands_bank_is_not_allowing_customers_to_buy_bitcoins',
# 'https://cointelegraph.com/news/university_of_nicosia_in_cyprus_is_first_in_the_world_to_accept_bitcoin',
# 'https://cointelegraph.com/news/litecion_s_pace_quickening_also',
# 'https://cointelegraph.com/news/reuters_global_investment_outlook_summit_day_3',
# 'https://cointelegraph.com/news/bitcoin_vs_dollar',
# 'https://cointelegraph.com/news/3_biggest_deceptions_about_bitcoin',
# 'https://cointelegraph.com/news/senate_committee_discussed_bitcoin_benefits',
# 'https://cointelegraph.com/news/family_raises_1_million_for_ross_ulbricht_s_bail',
# 'https://cointelegraph.com/news/game_company_running_secret_bitcoin_mining_op_to_settle_for_1_million',
# 'https://cointelegraph.com/news/airport_forex_kiosk_introduces_bitcoin_option_gets_overwhelmed',
# 'https://cointelegraph.com/news/will_bitcoin_go_down_a_treat_website_says_that_3_reward_could_help',
# 'https://cointelegraph.com/news/now_you_can_travel_with_bitcoin',
# 'https://cointelegraph.com/news/bitpay_passes_10_000_merchants_mark',
# 'https://cointelegraph.com/news/why_bitcoin_is_acting_like_a_bubble',
# 'https://cointelegraph.com/news/assassination_site_accepts_bitcoins_to_kill_american_officials',
# 'https://cointelegraph.com/news/bitcoin_s_increasing_legitimacy_sparks_rally_on_exchanges',
# 'https://cointelegraph.com/news/us_governments_tepid_approval_sends_btc_above_750',
# 'https://cointelegraph.com/news/justice_dept_digital_currencies_attract_money_criminals',
# 'https://cointelegraph.com/news/is_bitcoin_outgrowing_its_core_user_base',
# 'https://cointelegraph.com/news/bitstamp_site_goes_down_after_network_problem',
# 'https://cointelegraph.com/news/the_case_for_regulation',
# 'https://cointelegraph.com/news/bitcoin_called_legitimate_in_senate_soars_in_value',
# 'https://cointelegraph.com/news/another_take_on_the_senate_bitcoin_hearing',
# 'https://cointelegraph.com/news/private_money_how_it_differs_from_dollars',
# 'https://cointelegraph.com/news/american_officials_seeking_more_oversight_in_digital_currencies',
# 'https://cointelegraph.com/news/startup_aims_to_identify_bitcoins_that_come_from_suspicious_activity',
# 'https://cointelegraph.com/news/senate_recognizes_legitimate_benefits_of_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_but_what_about_gold',
# 'https://cointelegraph.com/news/bitcoin_s_value_rises_further_after_senate_hearing',
# 'https://cointelegraph.com/news/fast_food_paid_fast',
# 'https://cointelegraph.com/news/investors_putting_5_million_into_btc_china',
# 'https://cointelegraph.com/news/buy_sushi_for_bitcoin_in_maki_wrap_lyon_france',
# 'https://cointelegraph.com/news/regulation_it_s_coming',
# 'https://cointelegraph.com/news/why_leading_economists_are_not_fascinated_in_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_senate_hearing_preview',
# 'https://cointelegraph.com/news/bitcoin_how_china_is_leading_the_way',
# 'https://cointelegraph.com/news/bitcoin_price_hits_500',
# 'https://cointelegraph.com/news/us_government_slowly_showing_its_stance_on_bitcoin',
# 'https://cointelegraph.com/news/us_not_the_major_player_in_bitcoin_trading',
# 'https://cointelegraph.com/news/bitcion_startup_raises_more_than_47_000_for_philippines_relief',
# 'https://cointelegraph.com/news/proposal_to_track_bitcoins_sparks_communitywide_debate',
# 'https://cointelegraph.com/news/the_fbi_declared_what_they_actually_think_about_bitcoin',
# 'https://cointelegraph.com/news/on_keeping_your_bitcoins_secure',
# 'https://cointelegraph.com/news/baidu_services_to_be_paid_by_bitcoins',
# 'https://cointelegraph.com/news/paypal_co_founder_peter_thiel_on_bitcoin_s_potential_to_change_the_world',
# 'https://cointelegraph.com/news/bitcoin_ransomware_may_have_targeted_millions_in_uk',
# 'https://cointelegraph.com/news/first_bar_to_accept_bitcoin_in_china',
# 'https://cointelegraph.com/news/state_of_new_york_plans_to_hold_bitcoin_hearings',
# 'https://cointelegraph.com/news/first_children_s_book_on_alternative_currency',
# 'https://cointelegraph.com/news/the_first_bitcoin_atm_managed_100_000_worth_transactions_in_a_week',
# 'https://cointelegraph.com/news/senate_will_discuss_potentials_and_threats_of_digital_currency',
# 'https://cointelegraph.com/news/bitcoin_ransom_to_cryptolocker_malware',
# 'https://cointelegraph.com/news/senate_committee_reveals_speakers_at_bitcoin_hearing',
# 'https://cointelegraph.com/news/senate_banking_committee_invites_bitpay_and_ripple_to_speak',
# 'https://cointelegraph.com/news/coinsetter_s_private_beta_goes_online',
# 'https://cointelegraph.com/news/sweden_s_kncminer_earns_3_million_plus_in_just_four_days',
# 'https://cointelegraph.com/news/canada_s_alix_resources_paying_contractor_in_bitcoin',
# 'https://cointelegraph.com/news/her_majesty_s_revenue_customs_thinks_btc_might_be_taxable',
# 'https://cointelegraph.com/news/on_the_state_of_new_york_s_bitlicenses',
# 'https://cointelegraph.com/news/stockholm_s_kncminer_sells_3_million_in_mining_hardware_in_four_days',
# 'https://cointelegraph.com/news/the_bitcoin_universe_scammers_criminals_and_the_feds',
# 'https://cointelegraph.com/news/3d_printer_struggles_to_woo_bitcoin_spenders',
# 'https://cointelegraph.com/news/federal_elections_commission_might_allow_political_bitcoin_donations',
# 'https://cointelegraph.com/news/us_based_bitcoin_exchange_launches',
# 'https://cointelegraph.com/news/winklevoss_twins_predict_1_btc_will_be_worth_40_000',
# 'https://cointelegraph.com/news/askmen_com_lists_satoshi_nakamoto_among_most_influential_men',
# 'https://cointelegraph.com/news/us_subway_sandwich_shop_accept_bitcoins',
# 'https://cointelegraph.com/news/bitfunder_a_bitcoin_stock_exchange_closes',
# 'https://cointelegraph.com/news/hackers_attacked_czech_bitcoin_exchange_and_emptied_users_wallets',
# 'https://cointelegraph.com/news/soon_there_will_be_a_possibility_to_buy_politicians_with_digital_money',
# 'https://cointelegraph.com/news/itbit_raises_3_25m_to_create_a_new_bitcoin_commerce_platform',
# 'https://cointelegraph.com/news/new_bitcoin_exchange_itbit_get_off_the_ground_with_5_5m_in_funds',
# 'https://cointelegraph.com/news/reaching_boundaries_of_south_pole',
# 'https://cointelegraph.com/news/bitcoin_website_inputs_io_lost_1m_when_hackers_attacked_two_times',
# 'https://cointelegraph.com/news/bitcoin_isn_t_ready_for_prime_time_as_a_world_wide_remittance_replacement',
# 'https://cointelegraph.com/news/bitcoin_exchanger_coinx_is_undertaking_one_state_after_another',
# 'https://cointelegraph.com/news/winklevoss_brothers_hold_1_of_all_bitcoins',
# 'https://cointelegraph.com/news/miicard_reduces_the_time_in_buying_bitcoins',
# 'https://cointelegraph.com/news/bitcoin_prices_continue_to_climb_up',
# 'https://cointelegraph.com/news/is_bitcoin_broken_gavin_andresen_responds_to_mining_vulnerability_paper',
# 'https://cointelegraph.com/news/probably_the_useless_guide_to_despoiling_the_bitcoin_mine',
# 'https://cointelegraph.com/news/phenixcoin_no_code_no_coin',
# 'https://cointelegraph.com/news/gocoin_raises_550k_to_process_bitcoin_payments_in_asia_and_south_america',
# 'https://cointelegraph.com/news/first_bitcoin_atm_processed_348_transactions_in_8_days',
# 'https://cointelegraph.com/news/buy_a_sandwich_in_russia_pay_with_bitcoins_and_get_your_special_discount',
# 'https://cointelegraph.com/news/chairman_carper_statement_on_the_unveiling_of_the_so_called_silk_road_2_0_website',
# 'https://cointelegraph.com/news/people_have_bought_or_sold_100_000_in_bitcoins_from_a_vancouver_atm_firm_says',
# 'https://cointelegraph.com/news/famous_brazilian_magazine_increases_bitcoin_popularity',
# 'https://cointelegraph.com/news/absolute_bitcoin_price_record_reaches_300',
# 'https://cointelegraph.com/news/the_bitcoin_bubble',
# 'https://cointelegraph.com/news/bitcoin_might_be_appropriated_by_selfish_groups_bringing_to_currency_collapse',
# 'https://cointelegraph.com/news/what_happens_if_bitcoin_collapses_to_zero',
# 'https://cointelegraph.com/news/bitcoin_s_awesome_november_let_s_stop_calling_this_a_bubble',
# 'https://cointelegraph.com/news/australian_off_road_vehicle_company_accepting_bitcoins',
# 'https://cointelegraph.com/news/dutch_customers_can_now_order_food_online_with_bitcoin',
# 'https://cointelegraph.com/news/which_big_time_investors_are_betting_on_bitcoin',
# 'https://cointelegraph.com/news/alydian_a_coinlab_spin_off_files_for_bankruptcy',
# 'https://cointelegraph.com/news/iranian_shoemaker_bypasses_sanctions_with_bitcoin',
# 'https://cointelegraph.com/news/new_leader_in_world_s_bitcoin_exchange',
# 'https://cointelegraph.com/news/ebay_expand_the_range_of_digital_currencies_it_accepts',
# 'https://cointelegraph.com/news/bitcoin_in_india_drivers_and_barriers_to_adoption',
# 'https://cointelegraph.com/news/ebay_ceo_john_donahoe_is_bullish_on_digital_currency_and_he_s_keeping_tabs_on_bitcoin',
# 'https://cointelegraph.com/news/incoming_bitcoin_transaction_from_the_south_pole',
# 'https://cointelegraph.com/news/western_union_is_not_yet_ready_for_bitcoin_international_transfer',
# 'https://cointelegraph.com/news/75_years_in_prison_for_a_founder_of_digital_currency_service_liberty_reserve',
# 'https://cointelegraph.com/news/south_american_startup_moneero_creates_sms_bitcoin_payment_system',
# 'https://cointelegraph.com/news/dark_wallet_begins_indiegogo_campaign_to_crowdsource_funding',
# 'https://cointelegraph.com/news/us_bitcoin_startup_secures_9_million_in_funding',
# 'https://cointelegraph.com/news/bitcoin_changing_banking_system',
# 'https://cointelegraph.com/news/first_bitcoin_atm_in_vancouver_coffee_house',
# 'https://cointelegraph.com/news/bitcoin_development_and_the_necessity_of_regulations',
# 'https://cointelegraph.com/news/the_biggest_bitcoin_deal_in_history_of_bitpay',
# 'https://cointelegraph.com/news/silly_purchase_makes_a_new_millionaire',
# 'https://cointelegraph.com/news/australian_photography_studio_offers_50_discount_for_bitcoin_customers',
# 'https://cointelegraph.com/news/coinbase_aims_to_take_a_bigger_part_of_the_market_to_itself',
# 'https://cointelegraph.com/news/bitmit_ebay_for_coin_users',
# 'https://cointelegraph.com/news/the_second_life_for_namecoin',
# 'https://cointelegraph.com/news/new_btc_exchange_goes_live_in_australia',
# 'https://cointelegraph.com/news/the_biggest_bitcoin_exchange_company_from_africa_is_sold',
# 'https://cointelegraph.com/news/bitcoin_in_a_totally_new_light',
# 'https://cointelegraph.com/news/antique_shop_to_revolutionize_the_traditional_retail',
# 'https://cointelegraph.com/news/coinbase_enters_the_smartphones_of_bitcoin_users',
# 'https://cointelegraph.com/news/bitmarkers_move_bitcoins_in_las_vegas',
# 'https://cointelegraph.com/news/bigcommerce_pairs_up_with_bips_to_open_new_perspectives',
# 'https://cointelegraph.com/news/the_reasons_for_the_bitcoin_price_rise',
# 'https://cointelegraph.com/news/bitcoin_s_impact_on_homelessness',
# 'https://cointelegraph.com/news/religious_donations_in_bitcoins_why_not',
# 'https://cointelegraph.com/news/bitcoin_helps_to_avoid_issues_of_international_banking_system',
# 'https://cointelegraph.com/news/vault_of_satoshi_trip_to_canada',
# 'https://cointelegraph.com/news/bitcoins_enter_the_poland_market',
# 'https://cointelegraph.com/news/btcquick_the_quickest_bitcoin_seller',
# 'https://cointelegraph.com/news/physical_bank_account_closed_because_of_bitcoin',
# 'https://cointelegraph.com/news/trading_coffee_beans_via_bitcoin',
# 'https://cointelegraph.com/news/coinvoice_bitcoin_friendly_invoice_system',
# 'https://cointelegraph.com/news/black_shopping_becomes_fatal',
# 'https://cointelegraph.com/news/new_bitpay_pricelist_for_customers',
# 'https://cointelegraph.com/news/fbi_the_new_huge_bitcoin_dealer',
# 'https://cointelegraph.com/news/a_new_kind_of_money',
# 'https://cointelegraph.com/news/analysis_of_btc_e',
# 'https://cointelegraph.com/news/are_bitcoins_still_alive',
# 'https://cointelegraph.com/news/world_s_first_mt_everest_flight_and_bitcoin_logo_on_a_glider',
# 'https://cointelegraph.com/news/new_exchange_service_from_the_leading_bitcoin_market_player',
# 'https://cointelegraph.com/news/first_lamassu_bitcoin_atm',
# 'https://cointelegraph.com/news/silk_road_collapse_ross_ulbricht_arrested',
# 'https://cointelegraph.com/news/no_mining_for_zeroaccess',
# 'https://cointelegraph.com/news/closed_by_fbi_silk_road_website_has_reborn',
# 'https://cointelegraph.com/news/fsp_launches_a_bitcoin_rent_payment_project',
# 'https://cointelegraph.com/news/kncminer_finished_production_of_jupiter_bitcoin_mining_rigs',
# 'https://cointelegraph.com/news/mt_gox_founder_developing_new_digital_currency',
# 'https://cointelegraph.com/news/we_are_learning_more_about_dark_wallet',
# 'https://cointelegraph.com/news/processing_small_amounts_of_money',
# 'https://cointelegraph.com/news/atlantis_shuts_down_hindsight_suggests_it_was_a_scam_all_along',
# 'https://cointelegraph.com/news/understanding_state_level_money_transmission_licenses',
# 'https://cointelegraph.com/news/new_hampshire_lawmaker_raises_1_600_in_bitcoin',
# 'https://cointelegraph.com/news/terrahash_shutting_down_only_partially_refunding_customers',
# 'https://cointelegraph.com/news/the_curious_intersection_of_bitcoin_and_pre_history_societies',
# 'https://cointelegraph.com/news/germany_takes_the_lead_in_eu_bitcoin_popularity',
# 'https://cointelegraph.com/news/big_names_weigh_in_on_bitcoin',
# 'https://cointelegraph.com/news/the_realities_of_a_bitcoin_salary',
# 'https://cointelegraph.com/news/a_bitcoin_model_for_publishers',
# 'https://cointelegraph.com/news/gocoin_looks_to_singapore_for_success_in_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_and_anonymity',
# 'https://cointelegraph.com/news/mobile_bitcoin_wallet_lands_200k_in_funding',
# 'https://cointelegraph.com/news/a_look_at_7_bitcoin_startups_at_boost_vc_demo_day',
# 'https://cointelegraph.com/news/how_disruptive_can_bitcoin_be_for_banking',
# 'https://cointelegraph.com/news/bitpagos_adding_bitcoin_payment_processing_for_argentinian_customers',
# 'https://cointelegraph.com/news/a_roundup_of_recent_bitcoin_acceptance_milestones',
# 'https://cointelegraph.com/news/canada_ready_to_test_its_own_digital_system_for_money_transfer',
# 'https://cointelegraph.com/news/couple_living_on_bitcoin_able_to_pay_for_hotel_flights',
# 'https://cointelegraph.com/news/swiss_lawmaker_asks_for_national_report_on_bitcoin',
# 'https://cointelegraph.com/news/ripple_software_going_open_source',
# 'https://cointelegraph.com/news/bitcoin_price_fluctuations_becoming_more_predictable',
# 'https://cointelegraph.com/news/game_developer_bigpoint_to_accept_bitcoin_for_in_game_purchases',
# 'https://cointelegraph.com/news/xbt_the_bitcoin_currency_code',
# 'https://cointelegraph.com/news/the_number_of_bitpay_clients_has_reached_10_000',
# 'https://cointelegraph.com/news/popular_sydney_bar_to_accept_bitcoins',
# 'https://cointelegraph.com/news/bitcoin_computation_power_hits_one_petahash_per_second',
# 'https://cointelegraph.com/news/israeli_government_to_consider_tax_on_bitcoins',
# 'https://cointelegraph.com/news/international_task_force_exploring_criminal_ties_to_virtual_economies',
# 'https://cointelegraph.com/news/reclaiming_financial_privacy_with_digital_currencies',
# 'https://cointelegraph.com/news/california_amendment_to_money_transmission_act_a_benefit_to_bitcoin',
# 'https://cointelegraph.com/news/kraken_goes_live_for_cryptocurrency_traders',
# 'https://cointelegraph.com/news/bitcoin_atms_available_in_canada_by_year_s_end',
# 'https://cointelegraph.com/news/avalon_refunding_customers_with_outstanding_orders',
# 'https://cointelegraph.com/news/jon_matonis_takes_on_editorial_role_at_coindesk',
# 'https://cointelegraph.com/news/boston_eatery_enjoys_marketing_boost_from_bitcoin_acceptance',
# 'https://cointelegraph.com/news/hashfast_bitcoin_mining_asic_chip_begins_production',
# 'https://cointelegraph.com/news/california_passes_bill_that_should_help_bitcoin_businesses',
# 'https://cointelegraph.com/news/bitmonet_enables_publishers_to_accept_bitcoin_microtransactions',
# 'https://cointelegraph.com/news/opacity_problems_in_an_open_source_currency',
# 'https://cointelegraph.com/news/the_switchboard_five_tech_policy_posts_you_need_to_read_today',
# 'https://cointelegraph.com/news/donations_in_bitcoins_for_politicians_why_not',
# 'https://cointelegraph.com/news/the_slow_decline_of_bitcoin_s_biggest_exchange_in_one_chart',
# 'https://cointelegraph.com/news/bitfury_s_400_gh_s_miners_shipping_out',
# 'https://cointelegraph.com/news/is_bitcoin_a_currency',
# 'https://cointelegraph.com/news/washington_post_reader_argues_bitcoin_is_not_a_currency',
# 'https://cointelegraph.com/news/litecoin_is_this_an_improvement_over_bitcoin',
# 'https://cointelegraph.com/news/feathercoin_introduces_mechanism_to_protect_its_blockchain_from_attacks',
# 'https://cointelegraph.com/news/recognition_from_oxford_dictionary_how_is_that_for_bitcoin_legitimacy',
# 'https://cointelegraph.com/news/asicminer_slashes_price_of_blade_hardware_by_65',
# 'https://cointelegraph.com/news/how_us_regulators_received_bitcoin_proponents',
# 'https://cointelegraph.com/news/what_happened_at_the_us_regulators_bitcoin_meeting',
# 'https://cointelegraph.com/news/can_bitcoin_enable_the_fabled_micropayments_revolution_coinbase_thinks_it_s_worth_a_shot',
# 'https://cointelegraph.com/news/hong_kong_investment_company_is_betting_huge_on_bitcoin_mining',
# 'https://cointelegraph.com/news/new_currency_same_blockchain',
# 'https://cointelegraph.com/news/are_investors_trying_to_transfer_wealth_from_fiat_to_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_miners_the_boom_within_the_boom',
# 'https://cointelegraph.com/news/coinlab_startup_going_for_enterprise_level_miners',
# 'https://cointelegraph.com/news/bitcoin_what_has_washington_interested',
# 'https://cointelegraph.com/news/blockchain_info_site_refunding_users_stolen_bitcoins',
# 'https://cointelegraph.com/news/catching_everyone_up_on_bitcoin',
# 'https://cointelegraph.com/news/trsst_secure_blogging_messaging_platform_for_the_open_web',
# 'https://cointelegraph.com/news/bitcoin_payment_processing_and_high_risk_merchants',
# 'https://cointelegraph.com/news/mr_satoshi_goes_to_washington',
# 'https://cointelegraph.com/news/germany_is_first_to_offer_official_opinion_on_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_and_internet_gambling_a_natural_pairing',
# 'https://cointelegraph.com/news/android_vulnerability_to_blame_for_5_720_bitcoin_theft',
# 'https://cointelegraph.com/news/us_officials_to_investigate_digital_currencies_oversight',
# 'https://cointelegraph.com/news/new_york_and_u_s_examination_of_bitcoins',
# 'https://cointelegraph.com/news/senate_pressing_regulators_on_bitcoin_risks_and_oversight',
# 'https://cointelegraph.com/news/ny_regulator_may_break_down_on_bitcoin',
# 'https://cointelegraph.com/news/bitcoin_is_a_currency_federal_judge_says_virtual_money_is_a_real_currency',
# 'https://cointelegraph.com/news/slashdot_s_founder_talks_social_news_aggregators',
# 'https://cointelegraph.com/news/bitcoin_is_a_bikers_business',
# 'https://cointelegraph.com/news/bitcoin_exchange_mt_gox_reveals_technical_upgrades_to_boost_performance',
# 'https://cointelegraph.com/news/easic_s_new_miner_capable_of_24_th_s',
# 'https://cointelegraph.com/news/5_key_issues_facing_the_next_fed_chief',
# 'https://cointelegraph.com/news/more-attempts-to-bring-e-commerce-to-worlds-two-billion-unbanked-',
# 'https://cointelegraph.com/news/great-time-to-buy-bitcoin-as-unreliable-sources-from-china-spook-markets-',
# 'https://cointelegraph.com/news/coinbase-advises-users-to-transfer-btc-',
# 'https://cointelegraph.com/news/with-myetherwallet-phishing-surge-do-icos-need-to-use-slack-',
# 'https://cointelegraph.com/news/georgias-unipay-brings-bitcoin-to-55000-active-users-',
# 'https://cointelegraph.com/news/john-mcafee-to-run-for-us-president-after-creating-own-cyber-party-',
# 'https://cointelegraph.com/news/the-shemitah-are-we-just-days-away-from-global-economic-destruction-op-ed-',
# 'https://cointelegraph.com/news/british-pm-david-cameron-selects-bitcoin-company-for-asian-delegation-',
# 'https://cointelegraph.com/news/mapofcoins-unleashes-technologies-library-for-800-cryptocurrencies-to-facilitate-digital-learning-',
# 'https://cointelegraph.com/news/and-the-winners-of-cointelegraphs-2014-bitcoin-industry-awards-are-',
# 'https://cointelegraph.com/news/concerning-garza-tnabc-and-bitcoin-media-down-with-everything-associated-with-anyone-op-ed-',
# 'https://cointelegraph.com/news/i-wanted-to-be-a-part-of-something-special-much-like-i-did-in-helping-get-paypal-off-the-ground-',
# 'https://cointelegraph.com/news/founders-close-vault-of-satoshi-so-they-can-focus-on-new-business-',
# 'https://cointelegraph.com/news/new-york-state-bitcoin-is-intangible-property-',
# 'https://cointelegraph.com/news/weekend-roundup-dutch-banks-look-into-blockchains-btc-transactions-spike-and-companies-request-regulations-',
# 'https://cointelegraph.com/news/genecoin-developers-on-storing-dna-with-bitcoin-and-growing-blockchain-creatures-',
# 'https://cointelegraph.com/news/ichimoku-reversal-how-to-ride-the-bitcoin-bull-',
# 'https://cointelegraph.com/news/regulatory-compliance-has-proven-to-be-the-right-approach-brent-james-trucoin-',
# 'https://cointelegraph.com/news/bitcoin-to-business-congress-to-be-held-in-brussels-',
# 'https://cointelegraph.com/news/ubc-bitcoin-club-founder-willson-cross-charting-your-own-path-should-be-the-main-point-of-education-',
# 'https://cointelegraph.com/news/coin-academy-teams-up-with-college-cryptocurrency-network-to-fast-track-digital-currency-education-',
# 'https://cointelegraph.com/news/bitcoinexpo-2014-coming-to-shanghai-',
# 'https://cointelegraph.com/news/new-bitcoin-atms-first-machines-invade-ny-dallas-south-africa-',
# 'https://cointelegraph.com/news/the-chamber-of-digital-commerce-wants-you-to-educate-congress-',
# 'https://cointelegraph.com/news/yelps-director-of-public-policy-donates-10k-in-btc-towards-bitcoin-education-',
# 'https://cointelegraph.com/news/mt-gox-and-ripple-founders-secret-project-revealed-stellar-',
# 'https://cointelegraph.com/news/synccoin-asset-backed-pos-with-real-life-application-and-bountiful-rewards-',
# 'https://cointelegraph.com/news/the-russian-ministry-of-finance-one-step-closer-to-banning-bitcoin-',
# 'https://cointelegraph.com/news/gyft-acquired-by-leading-payment-service-provider-first-data-',
# 'https://cointelegraph.com/news/multi-coin-wallet-overview-frozenbit-and-coinomi-',
# 'https://cointelegraph.com/news/knc-on-the-cusp-of-delivering-titan-scrypt-miner-',
# 'https://cointelegraph.com/news/inside-bitcoins-is-coming-to-london-',
# 'https://cointelegraph.com/news/pawsitive-veterinary-care-',
# 'https://cointelegraph.com/news/mining-focused-hashers-united-conference-to-be-held-in-las-vegas-',
# 'https://cointelegraph.com/news/blackcoin-launches-blkfeed-and-blackcointalkorg-',
# 'https://cointelegraph.com/news/bitpay-uses-bitcoin-to-sponsor-georgia-tech-athletics-unveils-facebook-app-',
# 'https://cointelegraph.com/news/what-is-the-blockchain-',
# 'https://cointelegraph.com/news/btc-price-analysis-week-of-july-20-historical-weekly-overview-',
# 'https://cointelegraph.com/news/skilljar-aims-to-become-a-major-provider-of-online-education-courses-for-bitcoin-',
# 'https://cointelegraph.com/news/scrypt-mining-company-zeusminer-recruiting-farm-host-sites-',
# 'https://cointelegraph.com/news/anxpro-lowering-barriers-to-cryptocurrency-adoption-',
# 'https://cointelegraph.com/news/beepi-becomes-first-p2p-car-marketplace-to-accept-bitcoin-',
# 'https://cointelegraph.com/news/bitcoin-set-to-transform-the-courtroom-',
# 'https://cointelegraph.com/news/interview-with-zane-tackett-okcoin-',
# 'https://cointelegraph.com/news/mit-students-turn-out-unparalleled-bitcoin-visions-',
# 'https://cointelegraph.com/news/who-needs-atms-4000-btc-exchange-terminals-already-in-ukraine-',
# 'https://cointelegraph.com/news/first-major-european-newspaper-il-giornale-accepting-bitcoin-',
# 'https://cointelegraph.com/news/nerd-wars-amateur-hacker-makes-110k-from-gaming-data-',
# 'https://cointelegraph.com/news/fderp-short-only-hedge-fund-lets-you-bet-against-bitcoin-startups-',
# 'https://cointelegraph.com/news/cannabiscoin-meaner-greener-and-backed-by-marijuana-',
# 'https://cointelegraph.com/news/how-the-government-could-gain-access-to-your-smartphone-bitcoins-',
# 'https://cointelegraph.com/news/vericoin-to-open-cryptobank-pay-interest-to-users-',
# 'https://cointelegraph.com/news/38th-us-mint-director-to-keynote-bitcoin-expo-in-raleigh-',
# 'https://cointelegraph.com/news/offshore-tax-haven-jersey-aims-to-become-bitcoin-isle-',
# 'https://cointelegraph.com/news/3-of-overstock-profits-will-be-used-to-promote-bitcoin-',
# 'https://cointelegraph.com/news/cryptocurrency-defense-foundation-to-shield-community-from-patent-trolls-',
# 'https://cointelegraph.com/news/weekend-roundup-google-bing-yahoo-add-bitcoin-tools-japan-backs-off-and-bitcoin-at-the-2014-world-cup-',
# 'https://cointelegraph.com/news/vc-investment-rate-into-bitcoin-to-skyrocket-in-2014-',
# 'https://cointelegraph.com/news/education-to-consider-for-the-bitcoin-user-',
# 'https://cointelegraph.com/news/oversupply-of-bitcoin-will-burst-the-bubble',
# 'https://cointelegraph.com/news/bitcoin-price-hits-10000',
# 'https://cointelegraph.com/news/keiser-envisions-100000-bitcoin-high',
# 'https://cointelegraph.com/news/price-analysis-november-22-bitcoin-ethereum-bitcoin-cash-ripple-litecoin',
# 'https://cointelegraph.com/news/bitcoin-breaks-through-8000-following-massive-head-fake',
# 'https://cointelegraph.com/news/bitfinex-struggles-with-money-withdrawal-community-observers-predict-mtgox-scenario',
# 'https://cointelegraph.com/news/bitcoins-upcoming-segwit2x-hard-fork-put-in-laymans-terms',
# 'https://cointelegraph.com/news/industry-leaders-give-perspective-on-bitcoin-forks-some-advantages-many-problems',
# 'https://cointelegraph.com/news/why-does-bitcoin-fail-as-a-payment-system',
# 'https://cointelegraph.com/news/ethereum-based-icos-can-be-good-bad-or-ugly-but-ultimately-create-vibrant-ecosystem',
# 'https://cointelegraph.com/news/what-lessons-can-be-learnt-from-tezos-ico-debacle',
# 'https://cointelegraph.com/news/bbva-launching-blockchain-shipping-solution',
# 'https://cointelegraph.com/news/ethereum-classic-changes-boost-price-to-new-all-time-highs-over-30',
# 'https://cointelegraph.com/news/singularitynet-announces-36mln-ico-funding-for-ai-platform-expansion',
# 'https://cointelegraph.com/news/bitcoin-is-what-email-was-in-early-90s',
# 'https://cointelegraph.com/news/bitcoins-flurry-is-fear-of-missing-out-usb-trader-art-cashin',
# 'https://cointelegraph.com/news/novogratz-rubbishes-bitcoin-bubble-40000-in-december-2018',
# 'https://cointelegraph.com/news/why-bitcoin-continues-its-phenomenal-rise',
# 'https://cointelegraph.com/news/letter-from-supposed-confido-lawyer-promises-ico-investors-refund',
# 'https://cointelegraph.com/news/keiser-dollar-collapsing-against-bitcoin',
# 'https://cointelegraph.com/news/bitcoin-revolution-and-the-great-central-bank-divide',
# 'https://cointelegraph.com/news/karpeles-coin-mt-gox-founders-ico-plans-cause-community-outrage',
# 'https://cointelegraph.com/news/achain-founder-fork-theory-echoed-technical-discussions',
# 'https://cointelegraph.com/news/iranian-high-council-of-cyberspace-supports-proposals-to-regulate-cryptocurrencies',
# 'https://cointelegraph.com/news/roger-ver-has-a-new-bet-to-the-world',
# 'https://cointelegraph.com/news/bitcoin-price-surpasses-1000000-yen-as-japan-seizes-nearly-60-market-share',
# 'https://cointelegraph.com/news/increasing-adoption-demonstrated-by-huge-trading-weekend-for-bitcoin-soaring-prices-market-wide',
# 'https://cointelegraph.com/news/bitcoin-eyes-15k-in-2018-but-dont-ditch-forks-interview-with-ronnie-moas',
# 'https://cointelegraph.com/news/cryptocurrency-exchange-reimburses-victims-of-apparent-ico-scam-confido',
# 'https://cointelegraph.com/news/eos-to-talk-dacs-tokens-and-blockchain-powered-conscious-culture-at-blockshow-asia-2017',
# 'https://cointelegraph.com/news/samsung-wins-public-sector-blockchain-contract-for-korean-govt',
# 'https://cointelegraph.com/news/icos-are-absolutely-securities-says-former-sec-boss-amid-crypto-boom',
# 'https://cointelegraph.com/news/300-bln-is-a-drop-in-the-ocean-bitcoin-is-still-a-baby-and-cant-be-a-bubble',
# 'https://cointelegraph.com/news/bringing-blockchain-to-iot',
# 'https://cointelegraph.com/news/cryptocurrency-market-cap-breaches-300-bln-btc-dominates',

##-----------------------------

# 'https://cointelegraph.com/news/are-asian-investors-going-short-on-cryptocurrencies',
# 'https://cointelegraph.com/news/interview-with-business-development-director-victoria-vaughan',
# 'https://cointelegraph.com/news/bitcoin_sweden_conference_almost_here',
# 'https://cointelegraph.com/news/matthew_mellon_on_bitcoin_with_max_keiser',
# 'https://cointelegraph.com/news/internet_freedom_the_implications_of_bitcoin_on_the_global_economy_by_stefan_molyneux',
# 'https://cointelegraph.com/news/cosign_to_introduce_a_new_standard_for_bitcoin_wallet_security',
# 'https://cointelegraph.com/news/frenchman_prosecuted_for_mentioning_bitcoin_in_conversation',
# 'https://cointelegraph.com/news/biggest_known_bitcoin_purchase_a_500_000_villa',
# 'https://cointelegraph.com/news/dogecoin_delighted_by_speed_and_racing_sponsoring_josh_wise',
# 'https://cointelegraph.com/news/who_are_you_my_mysterious_bitcoin_user',
# 'https://cointelegraph.com/news/mastercoin_decentralizing_exchange',
# 'https://cointelegraph.com/news/iranian_officials_look_into_bitcoin',
# 'https://cointelegraph.com/news/crucial_fix_for_dogecoin',
# 'https://cointelegraph.com/news/the_coin_telegraph_weekly_review_march_8_14th',
# 'https://cointelegraph.com/news/anghami_music_streaming_went_bit',
# 'https://cointelegraph.com/news/10_worldwide_celebrities_and_their_relations_to_cryptocurrency',
# 'https://cointelegraph.com/news/luxembourg_first_to_adopt_acceptable_rules_for_bitcoin_businesses',
# 'https://cointelegraph.com/news/france_initiates_revision_of_bitcoin_regulation_on_the_union_level',
# 'https://cointelegraph.com/news/bitcoin_clients_in_jeopardy_after_the_discovery_of_a_linux_bug',
# 'https://cointelegraph.com/news/research_team_finds_a_way_to_pick_pocket_openssl_based_devices',
# 'https://cointelegraph.com/news/ireland_installs_its_first_bitcoin_atm',
# 'https://cointelegraph.com/news/us_leading_trading_educational_platform_embraces_btc_ltc',
# 'https://cointelegraph.com/news/microtransactions_the_future_of_online_economy',
# 'https://cointelegraph.com/news/senator_manchin_clamors_for_bitcoin_ban_in_the_usa',
# 'https://cointelegraph.com/news/mt_gox_hit_the_bottom_and_is_alive_again',
# 'https://cointelegraph.com/news/bitcoin_enthusiasts_of_ecuador_gather_up_for_the_first_time',
# 'https://cointelegraph.com/news/real_time_bitcoin_price_monitor',
# 'https://cointelegraph.com/news/what_future_awaits_bitcoin_exchanges',
# 'https://cointelegraph.com/news/colony_earth_a_society_built_on_bitcoin',
# 'https://cointelegraph.com/news/is_there_a_solution_for_bitcoin_volatile_nature',
# 'https://cointelegraph.com/news/highkart_com_available_only_for_btc',
# 'https://cointelegraph.com/news/solarcoin_to_bring_it_progress_and_environmental_protection_together',
# 'https://cointelegraph.com/news/smart_wristband_holds_digital_coins',
# 'https://cointelegraph.com/news/first_graphic_novel_bought_with_bitcoin',
# 'https://cointelegraph.com/news/digital_currency_from_russia',
# 'https://cointelegraph.com/news/cryptocurrencies_introduced_to_the_definition_of_money_by_washington_dpi',
# 'https://cointelegraph.com/news/bitcloud_global_network_based_on_cryptocoins',
# 'https://cointelegraph.com/news/new_bitcoin_exchange_service_is_going_to_predetermine_the_distribution_of_forces',
# 'https://cointelegraph.com/news/earthcoin_cryptocurrency_with_vision_and_ambition',
'https://cointelegraph.com/news/the_perspectives_of_bitcoin_in_africa',
'https://cointelegraph.com/news/connie_gallipi_proves_that_bitcoin_might_change_the_course_of_life',
'https://cointelegraph.com/news/voting_system_based_on_bitcoin_to_be_developed',
'https://cointelegraph.com/news/steve_stockman_on_freedom_bitcoin_and_future_of_the_country',
'https://cointelegraph.com/news/bit4coin_reviews_on_success_after_1000_sold_gift_cards_to_develop_new_ideas',
'https://cointelegraph.com/news/bringing_bitcoin_closer_to_hard_cash_in_italy',
'https://cointelegraph.com/news/israel_chooses_to_observe_and_report',
'https://cointelegraph.com/news/ebay_to_change_policy_on_bitcon_from_10th_february',
'https://cointelegraph.com/news/satoshi_square_held_in_london_for_the_first_time',
'https://cointelegraph.com/news/wedbush_securities_analyst_about_bitcoin',
'https://cointelegraph.com/news/goodbye_coinye_kanye_west_cleanses_the_alternative_currencies_environment',
'https://cointelegraph.com/news/nba_team_sacramento_kings_embraces_bitcoin',
'https://cointelegraph.com/news/rural_english_farm_to_be_booked_out_for_events',
'https://cointelegraph.com/news/bitcoin_a_topic_of_discussion_on_asian_financial_forum',
'https://cointelegraph.com/news/zerocoin_unable_to_merge_with_bitcoin_goes_independent',
'https://cointelegraph.com/news/blockchain_info_s_grand_prize_goes_to_a_teenager',
'https://cointelegraph.com/news/butterfly_labs_complete_backlogs_with_a_beck_of_wing',
'https://cointelegraph.com/news/bitcoins_are_enough_to_provide_bad_and_breakfast',
'https://cointelegraph.com/news/educative_coinscrum_bitcoin_business_networking_event_will_shake_london',
'https://cointelegraph.com/news/complex_retail_system_accepts_bitcoin',
'https://cointelegraph.com/news/two_beer_or_not_two_beer_the_question_is_for_bitcoin',
'https://cointelegraph.com/news/lemonade_stand_offers_refreshments_cookies_and_adorable_smiles_for_bitcoins',
'https://cointelegraph.com/news/bitcoin_capable_to_satisfy_the_primary_needs_of_humans',
'https://cointelegraph.com/news/buybitcoin_ph_the_newest_bitcoin_exchange_in_the_philippines',
'https://cointelegraph.com/news/bitcoin_legal_status_mirrored_on_a_political_map_while_being_called_speculative',
'https://cointelegraph.com/news/two_horse_race_of_2014_or_bitcoin_against_western_union',
'https://cointelegraph.com/news/winery_to_pay_with_bitcoin_this_time_new_zealand',
'https://cointelegraph.com/news/with_bitcoinafrica_trip',
'https://cointelegraph.com/news/the_botswana_don_quixote_in_fight_for_bitcoin_recognition',
'https://cointelegraph.com/news/janet_yellen_was_elected_to_be_the_chair_of_the_fed',
'https://cointelegraph.com/news/bitpos_launched_in_australia_to_turn_soon_into_a_secret_project',
'https://cointelegraph.com/news/digging_for_bitcoins_in_real_world',
'https://cointelegraph.com/news/chinese_sina_corporation_launched_a_bitcoin_statistics_platform',
'https://cointelegraph.com/news/how_far_will_lead_the_invention_of_new_cryptocurrencies',
'https://cointelegraph.com/news/not_all_bitcoins_go_to_heaven',
'https://cointelegraph.com/news/bitcoin_center_has_been_opened_in_new_york',
'https://cointelegraph.com/news/37coins_to_make_bitcoin_transactions_simpler',
'https://cointelegraph.com/news/blockchain_info_to_support_elsa_hammond_in_the_raw_for_pacific',
'https://cointelegraph.com/news/interest_and_positive_attitude_towards_bitcoin_proven_by_bank_of_japan',
'https://cointelegraph.com/news/bitcoin_started_to_ensure_healthcare_for_its_owners_in_2013',
'https://cointelegraph.com/news/the_exchange_service_mt_gox_to_enter_the_2014_with_new_features',
'https://cointelegraph.com/news/inside_bitcoin_day_2_11th_december',
'https://cointelegraph.com/news/how_much_antipode_is_the_attitude_of_australia_on_bitcoin',
'https://cointelegraph.com/news/ebay_requests_a_physical_guarantee_to_allow_selling_bitcoins',
'https://cointelegraph.com/news/no_sacred_status_for_bitcoin_in_india',
'https://cointelegraph.com/news/bitcoin_popularity_draws_attention_to_the_personality_of_satoshi_nakamoto',
'https://cointelegraph.com/news/joke_hits_the_price_of_bitcoin_and_avalanches_the_market',
'https://cointelegraph.com/news/aussies_coinjar_standing_tall_after_a_major_investment',
'https://cointelegraph.com/news/mysterious_transaction_of_194_993_btc',
'https://cointelegraph.com/news/first_aid_to_bitcoin_brokers_on_the_web',

			],
			'links_to_art': {'tag':'div','attr': 'class','attr_value': 'post boxed '},
		   'title': {'tag': 'h1','attr': 'class','attr_value': 'header'},
			'author': {'tag': 'div','attr': 'class','attr_value': 'name'},
            # 'date_time': {'tag': 'div', 'attr': 'class', 'attr_value': 'datetime'},
			#'date_time': {'tag': 'p', 'attr': 'itemprop', 'attr_value': 'datePublished'},
			'date_time': {'tag': 'script', 'attr': 'type', 'attr_value': 'application/ld+json'}, # парсинг даты статьи из json если json с ошибками
			'views': {'tag': 'div', 'attr': 'class', 'attr_value': 'referral_stats total-views'}, #'tag1': 'span', 'attr1': 'class', 'attr_value1': 'total-qty'}, # Views: (int)
			'shares': {'tag': 'div', 'attr': 'class', 'attr_value': 'referral_stats total-shares'},  # Shares: (int)
			'likes': {'tag': 'div', 'attr': 'class', 'attr_value': 'likes'},  # Likes: (int)
		   'body' : {'tag': 'div','attr': 'class', 'attr_value': 'post-full-text contents'},
		   'csv_name': 'cointelegraph.csv',
		   'short_link': False
               }
		  }

link_pattern = re.compile(r'^http.*\.\w*/(.*)')

# re.compile(r'^post-')